apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app  #a service for our app
  ports:
  - protocol: "TCP"
    port: 3000
    nodePort: 30080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app  #a deployment for our app
spec:
  selector:
    matchLabels:
      app: nodejs-app
  replicas: 2  #Number of replicas are 2 
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: is7aq/node-hello  #using the image we uploaded
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
